version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

